# Generated by Django 5.2.6 on 2025-10-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade_point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('A+', 'A+ (Outstanding)'), ('A', 'A (Excellent)'), ('B+', 'B+ (Very Good)'), ('B', 'B (Good)'), ('C+', 'C+ (Satisfactory)'), ('C', 'C (Acceptable)'), ('D+', 'D+ (Needs Improvement)'), ('D', 'D (Minimal)'), ('E', 'E (Insufficient)')], max_length=2),
        ),
    ]
